Traceback (most recent call last):
  File "/home/sean/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/sean/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/sean/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/sean/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/sean/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/sean/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/sean/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/sean/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
path_global = 'http://berkeleyearth.lbl.gov/auto/Global/Land_and_Ocean_summary.txt'
temp_data_global = pd.read_csv(path_global, header=None, delimiter=' ', comment = '%')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mParserError[0m                               Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m path_global [38;5;241m=[39m [38;5;124m'[39m[38;5;124mhttp://berkeleyearth.lbl.gov/auto/Global/Land_and_Ocean_summary.txt[39m[38;5;124m'[39m
[0;32m----> 2[0m temp_data_global [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_csv[49m[43m([49m[43mpath_global[49m[43m,[49m[43m [49m[43mheader[49m[38;5;241;43m=[39;49m[38;5;28;43;01mNone[39;49;00m[43m,[49m[43m [49m[43mdelimiter[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m [39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mcomment[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43m%[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py:610[0m, in [0;36mread_csv[0;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)[0m
[1;32m    605[0m kwds_defaults [38;5;241m=[39m _refine_defaults_read(
[1;32m    606[0m     dialect, delimiter, delim_whitespace, engine, sep, defaults[38;5;241m=[39m{[38;5;124m"[39m[38;5;124mdelimiter[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m,[39m[38;5;124m"[39m}
[1;32m    607[0m )
[1;32m    608[0m kwds[38;5;241m.[39mupdate(kwds_defaults)
[0;32m--> 610[0m [38;5;28;01mreturn[39;00m [43m_read[49m[43m([49m[43mfilepath_or_buffer[49m[43m,[49m[43m [49m[43mkwds[49m[43m)[49m

File [0;32m~/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py:468[0m, in [0;36m_read[0;34m(filepath_or_buffer, kwds)[0m
[1;32m    465[0m     [38;5;28;01mreturn[39;00m parser
[1;32m    467[0m [38;5;28;01mwith[39;00m parser:
[0;32m--> 468[0m     [38;5;28;01mreturn[39;00m [43mparser[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[43mnrows[49m[43m)[49m

File [0;32m~/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py:1057[0m, in [0;36mTextFileReader.read[0;34m(self, nrows)[0m
[1;32m   1055[0m [38;5;28;01mdef[39;00m [38;5;21mread[39m([38;5;28mself[39m, nrows[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m   1056[0m     nrows [38;5;241m=[39m validate_integer([38;5;124m"[39m[38;5;124mnrows[39m[38;5;124m"[39m, nrows)
[0;32m-> 1057[0m     index, columns, col_dict [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engine[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[43mnrows[49m[43m)[49m
[1;32m   1059[0m     [38;5;28;01mif[39;00m index [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1060[0m         [38;5;28;01mif[39;00m col_dict:
[1;32m   1061[0m             [38;5;66;03m# Any column is actually fine:[39;00m

File [0;32m~/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py:2061[0m, in [0;36mCParserWrapper.read[0;34m(self, nrows)[0m
[1;32m   2059[0m [38;5;28;01mdef[39;00m [38;5;21mread[39m([38;5;28mself[39m, nrows[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m   2060[0m     [38;5;28;01mtry[39;00m:
[0;32m-> 2061[0m         data [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_reader[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[43mnrows[49m[43m)[49m
[1;32m   2062[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:
[1;32m   2063[0m         [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_first_chunk:

File [0;32mpandas/_libs/parsers.pyx:756[0m, in [0;36mpandas._libs.parsers.TextReader.read[0;34m()[0m

File [0;32mpandas/_libs/parsers.pyx:771[0m, in [0;36mpandas._libs.parsers.TextReader._read_low_memory[0;34m()[0m

File [0;32mpandas/_libs/parsers.pyx:827[0m, in [0;36mpandas._libs.parsers.TextReader._read_rows[0;34m()[0m

File [0;32mpandas/_libs/parsers.pyx:814[0m, in [0;36mpandas._libs.parsers.TextReader._tokenize_rows[0;34m()[0m

File [0;32mpandas/_libs/parsers.pyx:1951[0m, in [0;36mpandas._libs.parsers.raise_parser_error[0;34m()[0m

[0;31mParserError[0m: Error tokenizing data. C error: Expected 2 fields in line 59, saw 91

ParserError: Error tokenizing data. C error: Expected 2 fields in line 59, saw 91


